### ISSUE TITLE
few questions about somaticwrapper

### ISSUE THREAD

**Issue by hfl112** [ding-lab/somaticwrapper#1]
Hi developers,
I am trying to apply this somaticwrapper and germlinewrapper to my data. I found there's a $DB_SNP_NO_COSMIC in somaticwrapper.pl, so is this vcf means excluded all the COSMIC mutations (both coding&noncoding) from DBSNP data? and is the DB_COSMIC the combined file of coding muts and non-coding muts from COSMIC?
And I found in your pipeline, you always run by steps, instead of run by samples. Is there an example of somaticwrapper ? it looks like you put all the files in a folder, but how to make the file structure? sample1.bam/bai + sample2.bam/bai? or have to specify tumor and normal in the file name?

by the way, I found another project from ding-lab said "VEP v85 is consistent with somaticwrapper 1.5", is VEP v88 compatible with the newest somaticwrapper now? 
and I also found you mentioned "Download dbSNP (b151) and filter somatic mutation sites using COSMIC_v89 VCF (download both of CosmicCoding and NonCoding VCFs from COSMIC). The filtered file is too big (*.vcf.gz >15GB) to share" in that file, is this the same to make $DB_SNP_NO_COSMIC file in somaticwrapper.

Sorry for I got so many questions, any help would be appreciated.
Thanks,
hfl

**Comment by caosgc33d** [comment]
DB_COSMIC contains both coding and non-coding muts.  You can dowonload cosmic and dbsnp vcf from their  database.
